version: "3.9"

services:
  web:
    build: .
    restart: always
    ports:
      - 80:80
    depends_on:
      - mariadb
    links:
      - mariadb
    environment:
      DB_HOST: mariadb
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: db
    volumes:
      - ..:/var/www/html
  mariadb:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./db-data:/var/lib/mysql
      - ./db-conf:/etc/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: db
